#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("com.example.android.wifidirect.Resource", IsApplication=true)]

namespace com.example.android.wifidirect
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040001
			public const int layout_border_color = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int status_bar_color = 2130968576;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050001
			public const int phone_list_height = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int tablet_list_width = 2131034112;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int details_view = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_action_discover = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_action_on_off = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_launcher = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Icon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int machine = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int section_header = 2130837510;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080012
			public const int atn_direct_discover = 2131230738;
			
			// aapt resource value: 0x7f080011
			public const int atn_direct_enable = 2131230737;
			
			// aapt resource value: 0x7f080000
			public const int btn_connect = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int btn_disconnect = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int btn_start_client = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int device_address = 2131230723;
			
			// aapt resource value: 0x7f080010
			public const int device_details = 2131230736;
			
			// aapt resource value: 0x7f080004
			public const int device_info = 2131230724;
			
			// aapt resource value: 0x7f08000f
			public const int device_name = 2131230735;
			
			// aapt resource value: 0x7f08000e
			public const int frag_detail = 2131230734;
			
			// aapt resource value: 0x7f08000d
			public const int frag_list = 2131230733;
			
			// aapt resource value: 0x7f080006
			public const int group_ip = 2131230726;
			
			// aapt resource value: 0x7f080005
			public const int group_owner = 2131230725;
			
			// aapt resource value: 0x7f080009
			public const int icon = 2131230729;
			
			// aapt resource value: 0x7f08000c
			public const int linearLayout1 = 2131230732;
			
			// aapt resource value: 0x7f08000a
			public const int my_name = 2131230730;
			
			// aapt resource value: 0x7f08000b
			public const int my_status = 2131230731;
			
			// aapt resource value: 0x7f080007
			public const int status_bar = 2131230727;
			
			// aapt resource value: 0x7f080008
			public const int status_text = 2131230728;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int device_detail = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int device_list = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int row_devices = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f070000
			public const int action_items = 2131165184;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060000
			public const int app_name = 2131099648;
			
			// aapt resource value: 0x7f060009
			public const int client_text = 2131099657;
			
			// aapt resource value: 0x7f060003
			public const int connect_peer_button = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int disconnect_peer_button = 2131099652;
			
			// aapt resource value: 0x7f060002
			public const int discover_peers_button = 2131099650;
			
			// aapt resource value: 0x7f060006
			public const int empty = 2131099654;
			
			// aapt resource value: 0x7f06000a
			public const int empty_message = 2131099658;
			
			// aapt resource value: 0x7f060001
			public const int enable_p2p_button = 2131099649;
			
			// aapt resource value: 0x7f060005
			public const int get_file_button = 2131099653;
			
			// aapt resource value: 0x7f06000c
			public const int group_owner_text = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int label_me = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int label_peers = 2131099662;
			
			// aapt resource value: 0x7f060008
			public const int no = 2131099656;
			
			// aapt resource value: 0x7f06000b
			public const int p2p_off_warning = 2131099659;
			
			// aapt resource value: 0x7f060007
			public const int yes = 2131099655;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
